apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: katehaki
global:
  resolve_timeout: 5m
  smtp_require_tls: true
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'phl23@ic.ac.uk'
    from: 'semlmonitor@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'semlmonitor@gmail.com'
    auth_identity: 'semlmonitor@gmail.com'
    auth_password: 'pxyvvquefcclhbrd'
  - to: 'zb23@ic.ac.uk'
    from: 'semlmonitor@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'semlmonitor@gmail.com'
    auth_identity: 'semlmonitor@gmail.com'
    auth_password: 'pxyvvquefcclhbrd'
  - to: 'ew1723@ic.ac.uk'
    from: 'semlmonitor@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'semlmonitor@gmail.com'
    auth_identity: 'semlmonitor@gmail.com'
    auth_password: 'pxyvvquefcclhbrd'
  - to: 'af723@ic.ac.uk'
    from: 'semlmonitor@gmail.com'
    smarthost: 'smtp.gmail.com:587'
    auth_username: 'semlmonitor@gmail.com'
    auth_identity: 'semlmonitor@gmail.com'
    auth_password: 'pxyvvquefcclhbrd'