apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: katehaki
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: web
      port: 9093
      targetPort: 9093
