apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: katehaki
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'aki-detection'
        static_configs:
          - targets: ['aki-detection:8080']
        metrics_path: '/metrics'
    rule_files:
      - '/etc/prometheus/rules/alerting-rules.yml'
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager:9093']