apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: katehaki
  # labels:
  #   app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          # args:
          #   - "--storage.tsdb.retention.time=12h"
          #   - "--config.file=/etc/prometheus/prometheus.yml"
          #   - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml"
              subPath: prometheus.yml
            - name: prometheus-alert-rules
              mountPath: /etc/prometheus/rules
      volumes:
        - name: prometheus-config
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-alert-rules
          configMap:
            defaultMode: 420
            name: prometheus-alert-rules
        - name: prometheus-storage
          emptyDir: {}