apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: katehaki
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    rule_files:
    - /etc/prometheus/prometheus-alerts.yaml
    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
          - targets:
            - "alertmanager-service.katehaki.svc.cluster.local:9093"
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: 'aki-detection'
        static_configs:
          - targets: ['aki-detection-service.katehaki.svc.cluster.local:8000']
        metrics_path: '/metrics'
